import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = 
[
  {
    "id": "gpcuHhSFsb4",
    "video_title": "৫ আগস্ট সকালে গনভবনে যা ঘটেছিল || Channel i News",
    "video_description": "৫ আগস্ট সকালে গনভবনে যা ঘটেছিল ================= প্রতিবেদক: সাজিদ আবদুল্লাহ সম্পাদনা: সাইফুজ্জামান ইমন  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Porta...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "gpcuHhSFsb4",
    "publish_date": "2025-05-06",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/gpcuHhSFsb4",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "8:08",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "CnVFRb1-RZg",
    "video_title": "তাহসান–রোজার বিচ্ছেদের কারণ জানালো ঘনিষ্ঠজনরা",
    "video_description": "শিরোনাম: তাহসান–রোজার বিচ্ছেদের কারণ জানালো ঘনিষ্ঠজনরা।   প্রতিবেদক- জেরিন সুমি Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelio...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "CnVFRb1-RZg",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/CnVFRb1-RZg",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:50",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "sKzhIiDzsF0",
    "video_title": "হুমায়ুন ফরীদি, সাধারণ একজন অসাধারণ",
    "video_description": "অভিনয়ের যাদুকর হুমায়ুন ফরীদির জন্মদিন আজ ==========  প্রতিবেদক : সুলতানা হিমু  সম্পাদনা :  সাইফুজ্জামান ইমন  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News ...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "sKzhIiDzsF0",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/sKzhIiDzsF0",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:56",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "C-Nw7rgGlj4",
    "video_title": "পারভেজ হ**ত্যা**র ঘটনায় সেই দুই নারী শিক্ষার্থী সাময়িক বহিষ্কার|| Channel i News",
    "video_description": "পারভেজ হ**ত্যা**র ঘটনায় সেই দুই নারী শিক্ষার্থী সাময়িক বহিষ্কার =================== প্রতিবেদক: পান্না আক্তার সম্পাদনা: সাইফুজ্জামান ইমন  Don’t forget to Subscribe, Follow, Share, Comment, like, and...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "C-Nw7rgGlj4",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/C-Nw7rgGlj4",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:24",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "Dn2HNY15pU0",
    "video_title": "সেনাবাহিনীর দেওয়া শা/স্তি সান্ডা ট্রেনিং নামে ভাইরাল! || Channel i News",
    "video_description": "সেনাবাহিনীর দেওয়া শা/স্তি সান্ডা ট্রেনিং নামে ভাইরাল!  প্রতিবেদক: সাজিদ আব্দুল্লাহ  সম্পাদনা: সাইফুজ্জামান ইমন  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online Ne...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "Dn2HNY15pU0",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/Dn2HNY15pU0",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:19",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "XwSoinFcqls",
    "video_title": "শরীয়তপুরে আধিপত্য বিস্তারকে কেন্দ্র করে তিন যুগে ধরে চলছে সং/ঘ/র্ষ",
    "video_description": "শরীয়তপুরে আধিপত্য বিস্তারকে কেন্দ্র করে তিন যুগে ধরে চলছে সং/ঘ/র্ষ ======================================== পদ্মার চরের বিলাসপুর ইউনিয়নে তিন দশকের আধিপত্যের বিরোধে ফের প্রাণহানি। বুধবারের সংঘর্ষের ...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "XwSoinFcqls",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/XwSoinFcqls",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:47",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "75CTQ0xEXG8",
    "video_title": "উত্তরায় স্বামী-স্ত্রীকে কু*পি*য়ে*ছে এরা কারা|| Channel i News",
    "video_description": "উত্তরায় স্বামী-স্ত্রীকে কু*পি*য়ে*ছে এরা কারা ================ প্রতিবেদক: পান্না আক্তার  সম্পাদনা: সাইফুজ্জামান ইমন  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Onl...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "75CTQ0xEXG8",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/75CTQ0xEXG8",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:37",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "48GVlifj6h4",
    "video_title": "মার্টিন লুথার কিং-এর যে কথায় অনুপ্রাণিত হয়েছেন তারেক রহমান",
    "video_description": "মার্টিন লুথার কিং-এর যে কথায় অনুপ্রাণিত হয়েছেন তারেক রহমান  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   Facebook...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "48GVlifj6h4",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/48GVlifj6h4",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:45",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "OmPz0mISEzo",
    "video_title": "তারেক রহমান বক্তব্য শেষে আবার মাইক্রোফোনে ফিরে আসা সাধারণ বিষয় নাকি শক্তিশালী কোন বার্তা!",
    "video_description": "Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   Facebook: https://www.facebook.com/channelionline https://www.facebo...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "OmPz0mISEzo",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/OmPz0mISEzo",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:09",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "wZbRUQT77B8",
    "video_title": "বেগম খালেদা জিয়া একজন মায়ের মুখ",
    "video_description": "বেগম খালেদা জিয়া একজন মায়ের মুখ ========================== প্রতিবেদক: তারিকুল ইসলাম মাসুম #channelinews #channeli #khaledazia #bnp #tariquerahman   Begum Khaleda Zia is one of Bangladesh’s most pro...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "wZbRUQT77B8",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/wZbRUQT77B8",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "20:02",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "TgMHS27OXjY",
    "video_title": "খালেদা জিয়া: প্রজ্ঞা, ত্যাগ ও সাহসিকতার প্রতীক এক মহীয়সী",
    "video_description": "খালেদা জিয়া: প্রজ্ঞা, ত্যাগ ও সাহসিকতার প্রতীক এক মহীয়সী ============================= বাংলাদেশের রাজনীতিতে এক কিংবদন্তীর নাম বেগম খালেদা জিয়া। দেশের স্বার্থ ও গণতন্ত্র পুনরুদ্ধারের সংগ্রামে আপসহীন...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "TgMHS27OXjY",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/TgMHS27OXjY",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "5:47",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "7UAk4jkQzjQ",
    "video_title": "খালেদা জিয়ার তিন আসনে এখন কী হবে | Channel i News",
    "video_description": "খালেদা জিয়ার তিন আসনে এখন কী হবে? | Channel i News #KhaledaZia #BangladeshPolitics #BNP #PoliticalUpdate #BangladeshNews #Election2025 #Shorts #YouTubeShorts  Don’t forget to Subscribe, Follow, Sha...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "7UAk4jkQzjQ",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/7UAk4jkQzjQ",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:27",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "bQKuvjkrSnM",
    "video_title": "তুমুল জনপ্রিয়তা আর ক্ষমতার অদৃশ্য মসনদের খুব কাছ থেকে একজন খালেদা জিয়ার প্রস্থান!",
    "video_description": "#channelinews #channeli #khaledazia #bnp #democracy   তুমুল জনপ্রিয়তা আর ক্ষমতার অদৃশ্য মসনদের খুব কাছ থেকে একজন খালেদা জিয়ার প্রস্থান!  Don’t forget to Subscribe, Follow, Share, Comment, like, and...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "bQKuvjkrSnM",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/bQKuvjkrSnM",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:15",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "eYKg8KeKNk8",
    "video_title": "খালেদা জিয়াকে নিয়ে জাইমা রহমানের আবেগঘন স্ট্যাটাস | Channel i News",
    "video_description": "Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   Facebook: https://www.facebook.com/channelionline https://www.facebo...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "eYKg8KeKNk8",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/eYKg8KeKNk8",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "4:08",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "piNIaydZM48",
    "video_title": "১০ ব‍্যাংক দেউলিয়া হয়ে গেছে, দুর্বল ব‍্যাংক, সবল ব‍্যাংক- অতিকথনের বছর",
    "video_description": "প্রতিবেদন ও উপস্থাপনা : রিজভী নেওয়াজ Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   Facebook: https://www.facebook....",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "piNIaydZM48",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/piNIaydZM48",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "8:42",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "zc19GPjX5H4",
    "video_title": "এখন কী সিদ্ধান্ত নেবে আইসিসি | Channel i News",
    "video_description": "এখন কী সিদ্ধান্ত নেবে আইসিসি | Channel i News  Bangladesh makes a dramatic stand against the T20 World Cup schedule, refusing to play matches in India. Following security issues involving Mustafizu...",
    "tags": ["National News", "Bangladesh", "Channel i", "News Report"],
    "cover_image": "zc19GPjX5H4",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/zc19GPjX5H4",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:55",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "BdCmH1WVAvg",
    "video_title": "মৃ/ত মানুষ ICU-তে? ব্যবসা নাকি ভুল ধারণা | Channel i News",
    "video_description": "Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   Facebook: https://www.facebook.com/channelionline https://www.facebo...",
    "tags": ["Explainer", "Analysis", "In-depth", "Channel i"],
    "cover_image": "BdCmH1WVAvg",
    "publish_date": "2026-01-10",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/BdCmH1WVAvg",
    "project_images": [],
    "category": ["Explainer", "Analysis"],
    "duration": "2:55",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "e4B5FK8KTbk",
    "video_title": "মোবাইল কি সত্যিই আমাদের কথা শোনে?",
    "video_description": "Do smartphones secretly listen to conversations to serve ads? Many believe so due to strange coincidences. We explore microphone permissions, \"Hey Google\" features, and how behavioral data—not co...",
    "tags": ["Explainer", "Analysis", "In-depth", "Channel i"],
    "cover_image": "e4B5FK8KTbk",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/e4B5FK8KTbk",
    "project_images": [],
    "category": ["Explainer", "Analysis"],
    "duration": "2:29",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "-ZlLveZdkzo",
    "video_title": "তীব্র শীত ভাঙল ৭২ বছরের রেকর্ড",
    "video_description": "তীব্র শীত ভাঙল ৭২ বছরের রেকর্ড ================= তীব্র শীতে কাঁপছে সারাদেশ। আবহাওয়াবিদরা বলছেন, এমন শীত নাকি গত ৭২ বছরের মধ্যে দেখেনি এই অঞ্চলের মানুষ। এখন প্রশ্ন উঠতে পারে এমন শীতের কারণ কী? #Cold...",
    "tags": ["Explainer", "Analysis", "In-depth", "Channel i"],
    "cover_image": "-ZlLveZdkzo",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/-ZlLveZdkzo",
    "project_images": [],
    "category": ["Explainer", "Analysis"],
    "duration": "4:59",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "EvFpH0ZprUI",
    "video_title": "ইতিহাস বলবে কারা বিশ্বাসঘাতক: মাদুরোর ছেলে",
    "video_description": "ইতিহাস বলবে কারা বিশ্বাসঘাতক: মাদুরোর ছেলে #channelinews #Venezuela #venezuelacrisis #uspolitics #trump #usarmy #maduroarrest #nicolasmaduro   Don’t forget to Subscribe, Follow, Share, Comment, lik...",
    "tags": ["Explainer", "Analysis", "In-depth", "Channel i"],
    "cover_image": "EvFpH0ZprUI",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/EvFpH0ZprUI",
    "project_images": [],
    "category": ["Explainer", "Analysis"],
    "duration": "2:00",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "FJdFinw23hI",
    "video_title": "এবার ভারতের বিরুদ্ধে ৫০০ শতাংশ শুল্ক চাপাচ্ছে যুক্তরাষ্ট্র",
    "video_description": "এবার ভারতের বিরুদ্ধে ৫০০ শতাংশ শুল্ক চাপাচ্ছে যুক্তরাষ্ট্র  US-India relations hit rock bottom as the US threatens a massive 500% tariff increase on Indian imports over India's continued purchase o...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "FJdFinw23hI",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/FJdFinw23hI",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "2:34",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "Ir4f4RH-jxE",
    "video_title": "ইরানের ৬ বিমানবন্দরে হাম লার দাবি ইসরায়েলের|| Channel i News",
    "video_description": "ইরানের ৬ বিমানবন্দরে হাম লার দাবি ইসরায়েলের ===================== প্রতিবেদক: আওসাফুল ইসলাম আকিফ সম্পাদনা: সাইফুজ্জামান ইমন #channelinews #iran #israel  Don’t forget to Subscribe, Follow, Share, Com...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "Ir4f4RH-jxE",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/Ir4f4RH-jxE",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "2:32",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "cdaLYk34R4Y",
    "video_title": "ভ্রমণ নিষেধাজ্ঞার তালিকা আরও বাড়াল ট্রাম্প, ফিলিস্তিনসহ যুক্ত হলো পাঁচ দেশ",
    "video_description": "ভ্রমণ নিষেধাজ্ঞার তালিকা আরও বাড়াল ট্রাম্প, ফিলিস্তিনসহ যুক্ত হলো পাঁচ দেশ ===================== প্রতিবেদক: পান্না আক্তার ভিডিও সম্পাদনা: সাইফুজ্জামান ইমন #Trump #TravelBan #USTravelBan #TrumpTrave...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "cdaLYk34R4Y",
    "publish_date": "2026-01-07",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/cdaLYk34R4Y",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "2:27",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "Q0f5ccVVdbE",
    "video_title": "সামরিক শক্তি বাড়ানোর ঘোষণা ট্রাম্পের",
    "video_description": "সামরিক শক্তি বাড়ানোর ঘোষণা ট্রাম্পের ============= প্রতিবেদক: মুসরাত শৈলী সম্পাদনা: সাইফুজ্জামান ইমন #ChanneliNews #Channeli #china #usa #taiwan #militaryclash   Don’t forget to Subscribe, Follow, ...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "Q0f5ccVVdbE",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/Q0f5ccVVdbE",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "2:39",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "nuHfJzevDz8",
    "video_title": "আকুর বিল পরিশোধে রিজার্ভ কমবে দুই বিলিয়ন || Channel i News",
    "video_description": "আকুর বিল পরিশোধে রিজার্ভ কমবে দুই বিলিয়ন =================== প্রতিবেদক: মাহবুব মোর্শেদ ভিডিও সম্পাদনা: সাইফুজ্জামান ইমন  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us. ...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "nuHfJzevDz8",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/nuHfJzevDz8",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "3:02",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "ixM8TsM4tRg",
    "video_title": "ভারতে ফের সাম্প্রদায়িক স হিংসতা, কা রফিউ জারি পুরো শহরে || Channel i News",
    "video_description": "ভারতে ফের সাম্প্রদায়িক স হিংসতা, কা রফিউ জারি পুরো শহরে =================== ভিকি কৌশাল অভিনীত বলিউডের ছাভা সিনেমা কে কেন্দ্র করে শুরু হয় আ ন্দোলন, সেই আ ন্দোলনে পুড়িয়ে দেয়া হয় মুঘল সম্রাট আওরঙ্গজে...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "ixM8TsM4tRg",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/ixM8TsM4tRg",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "3:38",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "H5DoI9jR4YU",
    "video_title": "২০২৬ সাল পৃথিবীতে যু/দ্ধ ও ধ্বংসের বছর | Baba Vanga | Channel i News",
    "video_description": "#BabaVanga #Vanga2026 #Geopolitics, #WorldWar, #IranCrisis, #Russia, #Channeli  ২০২৬ সাল পৃথিবীতে যু/দ্ধ ও ধ্বংসের বছর | Baba Vanga | Channel i News  Baba Vanga predicted 2026 would be a year of de...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "H5DoI9jR4YU",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/H5DoI9jR4YU",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "3:23",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "3Ew9-FarT5Y",
    "video_title": "ভেনেজুয়েলায় যুক্তরাষ্ট্রের হামলার পর উত্তর কোরিয়ার ব্যালিস্টিক ক্ষেপণাস্ত্র পরীক্ষা",
    "video_description": "ভেনেজুয়েলায় যুক্তরাষ্ট্রের হামলার পর উত্তর কোরিয়ার ব্যালিস্টিক ক্ষেপণাস্ত্র পরীক্ষা =================================== প্রতিবেদক: মিথুন রাজ ভিডিও সম্পাদনা: সাইফুজ্জামান ইমন #NorthKorea #MissileTes...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "3Ew9-FarT5Y",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/3Ew9-FarT5Y",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "1:49",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "0BMs6VijRRo",
    "video_title": "সাদ্দামের পর মাদুরোকে যেভাবে আটক করল ডেল্টা ফোর্স!",
    "video_description": "সাদ্দামের পর মাদুরোকে যেভাবে আটক করল ডেল্টা ফোর্স!  #DeltaForce #BlackHawkDown #venezuelacrisis  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: http...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "0BMs6VijRRo",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/0BMs6VijRRo",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "3:09",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "Teybv-v6hFA",
    "video_title": "ট্রাম্পের পরিকল্পনা যেনো থ্রিলার মুভিকেও  হার মানায়",
    "video_description": "ট্রাম্পের পরিকল্পনা যেনো থ্রিলার মুভিকেও  হার মানায়   US meticulously tracked Venezuelan President Maduro's life—food, clothes, pets. An elite squad trained on a mock-up of his residence, but bad ...",
    "tags": ["International News", "World News", "Channel i", "Global"],
    "cover_image": "Teybv-v6hFA",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/Teybv-v6hFA",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "3:31",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "-ZozFXMCXcM",
    "video_title": "রাওয়ালপিন্ডির পর ইসলামাবাদেও ১৪৪ ধারা জারি",
    "video_description": "রাওয়ালপিন্ডির পর ইসলামাবাদেও ১৪৪ ধারা জারি  প্রতিবেদক: Mithun Raj  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   ...",
    "tags": ["Breaking News", "International", "Live"],
    "cover_image": "-ZozFXMCXcM",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/-ZozFXMCXcM",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "1:53",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "Rx3BwM3gFIQ",
    "video_title": "চীনে নতুন ভাইরাসের সংক্রমণ, বিশ্ব জুড়ে আবারও মহামারির আশঙ্কা! || Channel i News",
    "video_description": "চীনে নতুন ভাইরাসের সংক্রমণ, বিশ্ব জুড়ে আবারও মহামারির আশঙ্কা! || Channel i News ========================== কোভিড-১৯ মহামারির পাঁচ বছর পর আবারও চীন করোনা সদৃশ দ্রুত সংক্রমক ভাইরাস, হিউমেন মেটানিউমোভ...",
    "tags": ["UN", "Diplomacy", "International"],
    "cover_image": "Rx3BwM3gFIQ",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/Rx3BwM3gFIQ",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "2:59",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "uImS5FACFqk",
    "video_title": "চীনের পর এবার ভারতে এইচএমপিভি ভাইরা--সের হানা || Channel i News",
    "video_description": "চীনের পর এবার ভারতে এইচএমপিভি ভাইরা--সের হানা ============================== প্রতিবেদক: আওসাফুল ইসলাম আকিফ সম্পাদনা: মোহিতুর রেজা  #channelinews #india #china #hmpv   Don’t forget to Subscribe, Fol...",
    "tags": ["Humanitarian", "Crisis", "International"],
    "cover_image": "uImS5FACFqk",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/uImS5FACFqk",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "2:14",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "AcoOvHmnXdI",
    "video_title": "দাবানল নেভাতে লস অ্যাঞ্জেলেসে আযানের ভিডিও ভাইরাল, কি বলছে ফ্যাক্টচেক",
    "video_description": "দাবানল নেভাতে লস অ্যাঞ্জেলেসে আযানের ভিডিও ভাইরাল, কি বলছে ফ্যাক্টচেক ========== প্রতিবেদক: মিঠুন রাজ সম্পাদনা: মোহিতুর রেজা খান  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay w...",
    "tags": ["Economy", "Markets", "International"],
    "cover_image": "AcoOvHmnXdI",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/AcoOvHmnXdI",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "1:23",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "3H2TOX6t4vg",
    "video_title": "ট্রাম্পের সঙ্গে মোদীর বৈঠক আয়োজনে মরিয়া ভারত|| Channel i News",
    "video_description": "ট্রাম্পের সঙ্গে মোদীর বৈঠক আয়োজনে মরিয়া ভারত ============================ প্রতিবেদক: আওসাফুল ইসলাম আকিফ সম্পাদনা: মোহিতুর রেজা  #channelinews #donaldtrump #norendramodi  Don’t forget to Subscribe,...",
    "tags": ["Diplomacy", "Visit", "International"],
    "cover_image": "3H2TOX6t4vg",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/3H2TOX6t4vg",
    "project_images": [],
    "category": ["International", "News"],
    "duration": "2:00",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "knW90t_E8Bg",
    "video_title": "২০২৫ সালে বিনোদন অঙ্গনে যাঁদের হারিয়েছি | Channel i News",
    "video_description": "২০২৫ সালে বিনোদন অঙ্গনে যাঁদের হারিয়েছি | Channel i News  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   Facebook: ...",
    "tags": ["Tribute", "Entertainment", "Culture", "National"],
    "cover_image": "knW90t_E8Bg",
    "publish_date": "2026-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/knW90t_E8Bg",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "5:51",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "Fd4D_sETgkM",
    "video_title": "বেগম খালেদা জিয়ার জন্য কাঁদছে বাংলাদেশ | Channel i News",
    "video_description": "বেগম খালেদা জিয়ার জন্য কাঁদছে বাংলাদেশ | Channel i News  Begum Khaleda Zia returned to the largest public assembly in Bangladesh history, but in silence. She was finally laid to rest beside her hus...",
    "tags": ["Infrastructure", "Development", "National"],
    "cover_image": "Fd4D_sETgkM",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/Fd4D_sETgkM",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:16",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "q4xjDa-Qa9E",
    "video_title": "ফুল সংগ্রহ করাই ছিল আমার হবি | Channel i News",
    "video_description": "ফুল সংগ্রহ করাই ছিল আমার হবি | Channel i News  In 1983, months after losing Ziaur Rahman, Khaleda Zia was away from the public eye. We revisit the rare 'Nipun' magazine feature that captured her qu...",
    "tags": ["Election", "Politics", "National"],
    "cover_image": "q4xjDa-Qa9E",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/q4xjDa-Qa9E",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:28",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "qJZ38cXTCG8",
    "video_title": "খালেদা জিয়ার মৃত্যু বিশ্ব গণমাধ্যমে যেভাবে উঠে এল || Khaleda Zia | International News Media",
    "video_description": "খালেদা জিয়ার মৃত্যু বিশ্ব গণমাধ্যমে যেভাবে উঠে এল || Khaleda Zia | International News Media ============================= একজন আপসহীন নেত্রী, একজন আমৃত্যু সংগ্রামী রাজনীতিবিদ, বাংলাদেশের অবিসংবাদিত...",
    "tags": ["Celebration", "Culture", "National"],
    "cover_image": "qJZ38cXTCG8",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/qJZ38cXTCG8",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:39",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "K7wPxDttWAU",
    "video_title": "এনসিপি থেকে পদত্যাগ করলেন জারা || Tasnim Zara | NCP | Resign",
    "video_description": "এনসিপি থেকে পদত্যাগ করলেন জারা || Tasnim Zara | NCP | Resign  ======================== এনসিপি থেকে পদত্যাগ করছেন দলটির জ্যেষ্ঠ যুগ্ম সদস্যসচিব থেকে পদত্যাগ করেছেন ডা. তাসনিম জারা। গণমাধ্যমের তথ্য, ...",
    "tags": ["Education", "Policy", "National"],
    "cover_image": "K7wPxDttWAU",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/K7wPxDttWAU",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:01",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "CNqQxTNZstc",
    "video_title": "কেরানীগঞ্জে উড়ে গেল মাদ্রাসার কক্ষ, বি স্ফো রক সরঞ্জাম উদ্ধার",
    "video_description": "কেরানীগঞ্জে উড়ে গেল মাদ্রাসার কক্ষ, বি স্ফো রক সরঞ্জাম উদ্ধার ============================ প্রতিবেদক: তন্ময় মাহমুদ ভিডিও সম্পাদনা: মোহিতুর রেজা খান   Don’t forget to Subscribe, Follow, Share, Comme...",
    "tags": ["Sports", "National", "Championship"],
    "cover_image": "CNqQxTNZstc",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/CNqQxTNZstc",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:10",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "3vnMPWub0xU",
    "video_title": "বগুড়ায় এসে যে বাড়িতে থাকতে পারেন তারেক রহমান",
    "video_description": "বগুড়ায় এসে যে বাড়িতে থাকতে পারেন তারেক রহমান  প্রতিবেদন : হারুন উর রশিদ ভিডিও সম্পাদনা : মোহিতুর রেজা খান  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Po...",
    "tags": ["Agriculture", "Rural", "National"],
    "cover_image": "3vnMPWub0xU",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/3vnMPWub0xU",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:11",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "Rg0Ynxaz3DI",
    "video_title": "সতেরো বছর ধরে পতাকা ফেরি করেন খোকন মুন্সি | Channel i News",
    "video_description": "Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   Facebook: https://www.facebook.com/channelionline https://www.facebo...",
    "tags": ["Urban", "Development", "National"],
    "cover_image": "Rg0Ynxaz3DI",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/Rg0Ynxaz3DI",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:51",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "aADqUQQj5XA",
    "video_title": "মোহাম্মদপুরে মা-মেয়ে হ/ত্যা: আসামি কি ধরা পড়বে?",
    "video_description": "মোহাম্মদপুরে মা-মেয়ে হ/ত্যা: আসামি কি ধরা পড়বে? ======================= রিপোর্টার: আওসাফুল ইসলাম আকিফ ভিডিও সম্পাদনা: মোহিতুর রেজা খান #ChanneliNews #Channeli #CrimeNews #lawandorder #Mohammadpur...",
    "tags": ["Health", "Government", "National"],
    "cover_image": "aADqUQQj5XA",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/aADqUQQj5XA",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:26",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "j_DwVSY8kLQ",
    "video_title": "রংপুরের তারাগঞ্জে স্ত্রীসহ মুক্তিযোদ্ধা হত্যা রহস্য",
    "video_description": "রংপুরের তারাগঞ্জে স্ত্রীসহ মুক্তিযোদ্ধা হত্যা রহস্য ============================ তারাগঞ্জ উপজেলার কুর্শা ইউনিয়নের রহিমাপুর গ্রামে রোববার আট ডিসেম্বর মর্মান্তিক হত্যাকাণ্ডের শিকার হন মুক্তিযোদ্ধা যো...",
    "tags": ["Legal", "Court", "National"],
    "cover_image": "j_DwVSY8kLQ",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/j_DwVSY8kLQ",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:20",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "oe1USnM3yNs",
    "video_title": "দেশে প্রাণীর প্রতি নিষ্ঠুরতার আলোচিত কিছু ঘটনা",
    "video_description": "Don’t forget to Subscribe, Follow, Share, Comment, like, and stay with us.  Online News Portal: https://www.channelionline.com   Facebook: https://www.facebook.com/channelionline https://www.facebo...",
    "tags": ["Environment", "Conservation", "National"],
    "cover_image": "oe1USnM3yNs",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/oe1USnM3yNs",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "3:35",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "WPTnUVGEZqo",
    "video_title": "উপদেষ্টা-সম্বয়কদের ফেইসবুক আইডি হ্যাকের বিষয়ে চাঞ্চল্যকর তথ্য || Channel i News",
    "video_description": "উপদেষ্টা-সম্বয়কদের ফেইসবুক আইডি হ্যাকের বিষয়ে চাঞ্চল্যকর তথ্য || Channel i News ============================ প্রতিবেদক: তন্ময় মাহমুদ ভিডিও সম্পাদনা: মোহিতুর রেজা খান  Don’t forget to Subscribe, Fol...",
    "tags": ["Trade", "Commerce", "National"],
    "cover_image": "WPTnUVGEZqo",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/WPTnUVGEZqo",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:39",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "mzbesP18EDw",
    "video_title": "খালেদা জিয়াকে নিজে গাড়ি চালিয়ে হাসপাতালে নিয়ে গেলেন তারেক রহমান || Channel i News BNP | Khaleda Zia",
    "video_description": "খালেদা জিয়াকে নিজে গাড়ি চালিয়ে হাসপাতালে নিয়ে গেলেন তারেক রহমান || Channel i News BNP | Khaleda Zia ===================================== দীর্ঘ প্রতীক্ষার পর উন্নত চিকিৎসার জন্য লন্ডনের মাটিতে পা র...",
    "tags": ["Weather", "Climate", "National"],
    "cover_image": "mzbesP18EDw",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/mzbesP18EDw",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:25",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  },
  {
    "id": "iYHrpYyf_yQ",
    "video_title": "দেশে আসছেন তারেক রহমান! || Khaleda Zia || Tarique Rahman  || Channel i News",
    "video_description": "দেশে আসছেন তারেক রহমান!  ================= প্রতিবেদক: তন্ময় মাহমুদ  ভিডিও সম্পাদনা: মোহিতুর রেজা খান #KhaledaZia  #Tarique Rahman  Don’t forget to Subscribe, Follow, Share, Comment, like, and stay ...",
    "tags": ["Culture", "Heritage", "National"],
    "cover_image": "iYHrpYyf_yQ",
    "publish_date": "2025-01-01",
    "client_name": "Channel i News",
    "client_image": "/companies/channel-i.png",
    "client_feedback": "",
    "video_link": "https://youtu.be/iYHrpYyf_yQ",
    "project_images": [],
    "category": ["National", "News"],
    "duration": "2:32",
    "software_used": ["Adobe Premiere Pro", "After Effects"]
  }
];
